### ISSUE TITLE
Add auth to redis?

### ISSUE THREAD

**Issue by mbejda** [timebug/lua-resty-limit-req#1]
Add auth option to the Redis configuration?

**Comment by yfgu** [comment]
red:auth(rds.pass)
        red:select(rds.dbid)

**Comment by timebug** [comment]
Hi, I just now adding `rds.pass` and `rds.dbid` option to the Redis configuration.

https://github.com/timebug/lua-resty-limit-req/commit/1ffa2f3d639d6e94658f7d18f16e241d744f9ff5

thanks. sorry that I have delayed so long.
