### ISSUE TITLE
Can I use lua-resty-http-master

### ISSUE THREAD

**Issue by yfgu** [timebug/lua-resty-limit-req#3]
In your README.md, it seems that we should install HttpLuaModule(ngx_http_lua_module). Can I use lua-resty-http-master instead of ngx_http_lua_module?

**Comment by timebug** [comment]
You can not only use lua-resty-http-master library. Because lua-resty-* libraries is build on ngx_http_lua_module. I recommend you to use OpenResty which already built-in ngx_http_lua_module.
