### ISSUE TITLE
能解释一下公式么？

### ISSUE THREAD

**Issue by yfgu** [timebug/lua-resty-limit-req#5]
不理解以下的公式，能麻烦解释一下么？
  local ms = math.abs(now - last)
  excess = excess - rate * ms / 1000 + 1000

**Comment by yfgu** [comment]
如果200并发/s,每5毫秒放进1个么？对于同时进入的请求，那是不是就会基本全部拒掉。

**Comment by timebug** [comment]
> 如果200并发/s,每5毫秒放进1个么？对于同时进入的请求，那是不是就会基本全部拒掉。

对于 200r/s 的请求，差不多允许通过的请求间隔是 5 毫秒，小于这个间隔的请求会被拒绝。

**Comment by timebug** [comment]
> 不理解以下的公式，能麻烦解释一下么？
> local ms = math.abs(now - last)
> excess = excess - rate * ms / 1000 + 1000

WIKI 关于漏桶算法的一些解释：https://en.wikipedia.org/wiki/Leaky_bucket

首先，我们把单位先转换下，5r/s 表示 1s 内可以按 200ms 间隔通过 5 个请求，我们这里把单位 r（请求）放大 1000 倍，单位假设为 t（水滴），`rate` = 5r/s = 5000t/s。

`ms` 为当前请求和上一个请求的时间间隔，单位毫秒（ms），假设 now-last 为 100ms，100ms/1000 = 0.1s，算出 rate * ms / 1000 = 5000t/s * 0.1s = 500t（500 个水滴）。

> 再来看这个完整的公式：excess = excess - rate * ms / 1000 + 1000

`excess` 表示上一次超出的水滴数（延迟通过）；特别地，`excess` < 0 的时候会被重置为 0，此时相当于漏桶处于空桶状态，进来的水滴直接流出了。

`excess` 初始化为 0；`excess` - `rate` * ms/1000 表示上一次延迟剩余的水滴数减去 ms 时间间隔内流出去的水滴数，按上面假设，100ms 内，流失 500t 水滴，最后 + 1000 表示算上当前这次请求（1 个请求 = 1000 个水滴）。

最终如果 `excess` > 0 说明漏桶有水滴堆积了，按我们设计，返回 BUSY，表示繁忙。

![image](https://user-images.githubusercontent.com/416154/29826364-9d09bc54-8d09-11e7-92de-d95de8952cbd.png)

**Comment by yfgu** [comment]
明白了，谢谢！
