### ISSUE TITLE
Weird behaviour in throttling requests

### ISSUE THREAD

**Issue by pzystorm** [timebug/lua-resty-limit-req#8]
Hi,
someone available for help?
I have a weird problem. Very simple configuration: One openresty, one backend server and one client which connects to the openresty (thats me).
I have the same configuration like your sample on the main page, I have just copied the whole stuff as a first test. 
To make it even more easier my zone name is identical to the throttle value: 2000r/s
`local lim, err = ratelimit.new(throttlevalue, throttlevalue, 0, 0)`
No burst, no duration.
Redis is only used by OpenResty (that means, by this test). Thus, no conflicts with zone names.
With the redis-cli I can see some entries (redis-cli GET "2000r/s:53")
53 is just a test, in this case: the query string. I call my test page via http://localhost/?53
While executing HTTP requests I see changing the redis values:
At one second: "[0,1562361116148,0]"
A bit later: "[0,1562361134727,0]"

Now the problem:
Look at this Kibana page:
![image](https://user-images.githubusercontent.com/765650/60745878-881eed00-9f7c-11e9-8fa9-fd4dd0c77ce3.png)
All my requests are pushed to Kibana and I am wondering why I sometimes get a HTTP 404 because of throttling. Look at the topmost five requests. They are done in the in the same second (have more detailled look at the msec column... they are all within 150ms).
But why one of these five requests is throttled?

At the moment I am a bit helpless... because 2000r/s is not reached... and the code is throttling requests...

There are no more requests... you can see all requests on that Kibana page... nothing is filtered...

Thanks :)

**Comment by pzystorm** [comment]
I have debugged it: in my case state is _M.BUSY
https://github.com/timebug/lua-resty-redis-ratelimit/blob/24287707a23a87aeabcd4ad429ad749779eefbad/lib/resty/redis/ratelimit.lua#L228-L230

So... it should be this problem:
http://granitosaurus.rocks/redis-busy.html

**Comment by timebug** [comment]
Hi, @pzystorm 

`_M.BUSY` is just means the request is excess, it has nothing to do with `redis-busy problem`. see: https://github.com/timebug/lua-resty-redis-ratelimit/blob/24287707a23a87aeabcd4ad429ad749779eefbad/lib/resty/redis/ratelimit.lua#L68

2000r/s that means two requests per millisecond are allowed. In this case, because of the time accuracy, it's hard to trigger `_M.BUSY`.

I suggest you try `20r/s` for test.

**Comment by pzystorm** [comment]
Ah ok, thanks for the answer, good to know!
Although I have set up 2000r/s, I can really easily reproduce the _M.BUSY answer.
I have just sent 5 request within 150ms and one of them gets throttled. Very easily to reproduce.
This is what I dont understand.

**Comment by timebug** [comment]
@pzystorm this library behavior is just like http://nginx.org/en/docs/http/ngx_http_limit_req_module.html, I recommend testing it with the same configuration.
